name: Deploy Frontend to Staging or Prod

on:
  push:
    branches:
      # - staging
      # - main
      # - devops/ci # FOR TESTS
      - no_branch
  # pull_request:
  #   branches:
  #     - staging
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker Image for Frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APP }}:${{ github.sha }} -f ./Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APP }}:${{ github.sha }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APP }}:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APP }}:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APP }}:latest
