name: Test Frontend

on:
  push:
    branches:
      - develop
      - staging
      - main
      - devops/ci # FOR TESTS
  pull_request:
    branches:
      - develop
      - staging
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
